<?php

namespace ContainerPHCGSDx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Tkc8p20Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tkc8p20' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tkc8p20'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'eventDispatcher' => ['services', 'event_dispatcher', 'getEventDispatcherService', false],
            'logger' => ['privates', 'monolog.logger', 'getMonolog_LoggerService', false],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
            'verificationRequestRepository' => ['privates', 'App\\Repository\\VerificationRequestRepository', 'getVerificationRequestRepositoryService', true],
            'verificationRequestValidator' => ['privates', '.errored.mElIkZt', NULL, 'Cannot determine controller argument for "App\\Controller\\Locastic\\VerificationRequest\\InitiateVerificationRequestAction::__invoke()": the $verificationRequestValidator argument is type-hinted with the non-existent class or interface: "App\\Validation\\VerificationRequest\\VerificationRequestValidatorInterface".'],
        ], [
            'eventDispatcher' => '?',
            'logger' => '?',
            'security' => '?',
            'verificationRequestRepository' => 'App\\Repository\\VerificationRequestRepository',
            'verificationRequestValidator' => '?',
        ]);
    }
}
