<?php

namespace ContainerPHCGSDx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GDUDmgQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gDUDmgQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gDUDmgQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'data' => ['privates', '.errored..service_locator.gDUDmgQ.App\\Entity\\Blog', NULL, 'Cannot autowire service ".service_locator.gDUDmgQ": it references class "App\\Entity\\Blog" but no such service exists.'],
            'eventDispatcher' => ['services', 'event_dispatcher', 'getEventDispatcherService', false],
        ], [
            'data' => 'App\\Entity\\Blog',
            'eventDispatcher' => '?',
        ]);
    }
}
