<?php

namespace ContainerBQIoBOv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVerificationRequest2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.iEquwsq.App\Entity\VerificationRequest' shared service.
     *
     * @return \App\Entity\VerificationRequest
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.iEquwsq": it references class "App\\Entity\\VerificationRequest" but no such service exists.');
    }
}
