<?php

namespace ContainerP8a7gyt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInitiateVerificationRequestSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventSubscriber\InitiateVerificationRequestSubscriber' shared autowired service.
     *
     * @return \App\EventSubscriber\InitiateVerificationRequestSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventSubscriber/InitiateVerificationRequestSubscriber.php';

        return $container->privates['App\\EventSubscriber\\InitiateVerificationRequestSubscriber'] = new \App\EventSubscriber\InitiateVerificationRequestSubscriber(($container->privates['App\\Service\\FileUploader'] ?? $container->load('getFileUploaderService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
