<?php

namespace ContainerMOJ4sZj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ce33EhBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ce33EhB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ce33EhB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\Locastic\\User\\RegisterUserControllerAction::__invoke' => ['privates', '.service_locator.aDz1WHK', 'get_ServiceLocator_ADz1WHKService', true],
            'App\\Controller\\Locastic\\VerificationRequest\\ApproveVerificationRequestAction::__invoke' => ['privates', '.service_locator.ws9Pbua', 'get_ServiceLocator_Ws9PbuaService', true],
            'App\\Controller\\Locastic\\VerificationRequest\\DeclineVerificationRequestAction::__invoke' => ['privates', '.service_locator.ws9Pbua', 'get_ServiceLocator_Ws9PbuaService', true],
            'App\\Controller\\Locastic\\VerificationRequest\\InitiateVerificationRequestAction::__invoke' => ['privates', '.service_locator.iEquwsq', 'get_ServiceLocator_IEquwsqService', true],
            'App\\Controller\\Locastic\\VerificationRequest\\UpdateVerificationRequestAction::__invoke' => ['privates', '.service_locator.WVn.d1m', 'get_ServiceLocator_WVn_D1mService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\Locastic\\User\\RegisterUserControllerAction:__invoke' => ['privates', '.service_locator.aDz1WHK', 'get_ServiceLocator_ADz1WHKService', true],
            'App\\Controller\\Locastic\\User\\RegisterUserControllerAction' => ['privates', '.service_locator.aDz1WHK', 'get_ServiceLocator_ADz1WHKService', true],
            'App\\Controller\\Locastic\\VerificationRequest\\ApproveVerificationRequestAction:__invoke' => ['privates', '.service_locator.ws9Pbua', 'get_ServiceLocator_Ws9PbuaService', true],
            'App\\Controller\\Locastic\\VerificationRequest\\ApproveVerificationRequestAction' => ['privates', '.service_locator.ws9Pbua', 'get_ServiceLocator_Ws9PbuaService', true],
            'App\\Controller\\Locastic\\VerificationRequest\\DeclineVerificationRequestAction:__invoke' => ['privates', '.service_locator.ws9Pbua', 'get_ServiceLocator_Ws9PbuaService', true],
            'App\\Controller\\Locastic\\VerificationRequest\\DeclineVerificationRequestAction' => ['privates', '.service_locator.ws9Pbua', 'get_ServiceLocator_Ws9PbuaService', true],
            'App\\Controller\\Locastic\\VerificationRequest\\InitiateVerificationRequestAction:__invoke' => ['privates', '.service_locator.iEquwsq', 'get_ServiceLocator_IEquwsqService', true],
            'App\\Controller\\Locastic\\VerificationRequest\\InitiateVerificationRequestAction' => ['privates', '.service_locator.iEquwsq', 'get_ServiceLocator_IEquwsqService', true],
            'App\\Controller\\Locastic\\VerificationRequest\\UpdateVerificationRequestAction:__invoke' => ['privates', '.service_locator.WVn.d1m', 'get_ServiceLocator_WVn_D1mService', true],
            'App\\Controller\\Locastic\\VerificationRequest\\UpdateVerificationRequestAction' => ['privates', '.service_locator.WVn.d1m', 'get_ServiceLocator_WVn_D1mService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\Locastic\\User\\RegisterUserControllerAction::__invoke' => '?',
            'App\\Controller\\Locastic\\VerificationRequest\\ApproveVerificationRequestAction::__invoke' => '?',
            'App\\Controller\\Locastic\\VerificationRequest\\DeclineVerificationRequestAction::__invoke' => '?',
            'App\\Controller\\Locastic\\VerificationRequest\\InitiateVerificationRequestAction::__invoke' => '?',
            'App\\Controller\\Locastic\\VerificationRequest\\UpdateVerificationRequestAction::__invoke' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\Locastic\\User\\RegisterUserControllerAction:__invoke' => '?',
            'App\\Controller\\Locastic\\User\\RegisterUserControllerAction' => '?',
            'App\\Controller\\Locastic\\VerificationRequest\\ApproveVerificationRequestAction:__invoke' => '?',
            'App\\Controller\\Locastic\\VerificationRequest\\ApproveVerificationRequestAction' => '?',
            'App\\Controller\\Locastic\\VerificationRequest\\DeclineVerificationRequestAction:__invoke' => '?',
            'App\\Controller\\Locastic\\VerificationRequest\\DeclineVerificationRequestAction' => '?',
            'App\\Controller\\Locastic\\VerificationRequest\\InitiateVerificationRequestAction:__invoke' => '?',
            'App\\Controller\\Locastic\\VerificationRequest\\InitiateVerificationRequestAction' => '?',
            'App\\Controller\\Locastic\\VerificationRequest\\UpdateVerificationRequestAction:__invoke' => '?',
            'App\\Controller\\Locastic\\VerificationRequest\\UpdateVerificationRequestAction' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
