<?php

namespace Container0HXx81T;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlogDataPersisterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\DataPersister\BlogDataPersister' shared autowired service.
     *
     * @return \App\DataPersister\BlogDataPersister
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/DataPersister/BlogDataPersister.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/Bridge/Doctrine/Common/DataPersister.php';

        return $container->privates['App\\DataPersister\\BlogDataPersister'] = new \App\DataPersister\BlogDataPersister(new \ApiPlatform\Core\Bridge\Doctrine\Common\DataPersister(($container->services['doctrine'] ?? $container->getDoctrineService())), ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));
    }
}
