<?php

namespace ContainerFqz6IBr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLocasticMailerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\LocasticMailer' shared autowired service.
     *
     * @return \App\Service\LocasticMailer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/LocasticMailer.php';

        return $container->privates['App\\Service\\LocasticMailer'] = new \App\Service\LocasticMailer(($container->privates['parameter_bag'] ?? ($container->privates['parameter_bag'] = new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container))), ($container->services['router'] ?? $container->getRouterService()), ($container->services['swiftmailer.mailer.default'] ?? $container->load('getSwiftmailer_Mailer_DefaultService')), ($container->services['twig'] ?? $container->getTwigService()));
    }
}
