<?php

namespace ContainerXLDzJ0G;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNonDuplicateVerificationRequestValidatorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Validation\VerificationRequest\NonDuplicateVerificationRequestValidator' shared autowired service.
     *
     * @return \App\Validation\VerificationRequest\NonDuplicateVerificationRequestValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Validation/VerificationRequest/NonDuplicateVerificationRequestValidator.php';

        return $container->privates['App\\Validation\\VerificationRequest\\NonDuplicateVerificationRequestValidator'] = new \App\Validation\VerificationRequest\NonDuplicateVerificationRequestValidator(($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')), ($container->privates['App\\Repository\\VerificationRequestRepository'] ?? $container->load('getVerificationRequestRepositoryService')));
    }
}
