<?php

namespace ContainerXLDzJ0G;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVerificationRequestParameterValidatorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Validation\VerificationRequest\VerificationRequestParameterValidator' shared autowired service.
     *
     * @return \App\Validation\VerificationRequest\VerificationRequestParameterValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Validation/VerificationRequest/VerificationRequestParameterValidator.php';

        return $container->privates['App\\Validation\\VerificationRequest\\VerificationRequestParameterValidator'] = new \App\Validation\VerificationRequest\VerificationRequestParameterValidator();
    }
}
