<?php

namespace ContainerL9jLZrI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAccessTokenValidatorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Validation\AccessTokenValidator' shared autowired service.
     *
     * @return \App\Validation\AccessTokenValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Validation/AccessTokenValidator.php';

        return $container->privates['App\\Validation\\AccessTokenValidator'] = new \App\Validation\AccessTokenValidator(($container->services['lexik_jwt_authentication.encoder'] ?? $container->load('getLexikJwtAuthentication_EncoderService')), ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService()), ($container->privates['App\\Repository\\UserAuthorizedAppRepository'] ?? $container->load('getUserAuthorizedAppRepositoryService')), ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')));
    }
}
