<?php

namespace ContainerL9jLZrI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddScopeControllerActionService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\Gatekeeper\Microservices\AddScopeControllerAction' shared autowired service.
     *
     * @return \App\Controller\Gatekeeper\Microservices\AddScopeControllerAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/Gatekeeper/Microservices/AddScopeControllerAction.php';

        return $container->services['App\\Controller\\Gatekeeper\\Microservices\\AddScopeControllerAction'] = new \App\Controller\Gatekeeper\Microservices\AddScopeControllerAction();
    }
}
