<?php

namespace ContainerL9jLZrI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiGuardAuthenticatorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Security\ApiGuardAuthenticator' shared autowired service.
     *
     * @return \App\Security\ApiGuardAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/EntryPoint/AuthenticationEntryPointInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-guard/AuthenticatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-guard/AbstractGuardAuthenticator.php';
        include_once \dirname(__DIR__, 4).'/src/Security/ApiGuardAuthenticator.php';

        return $container->privates['App\\Security\\ApiGuardAuthenticator'] = new \App\Security\ApiGuardAuthenticator(($container->services['lexik_jwt_authentication.encoder'] ?? $container->load('getLexikJwtAuthentication_EncoderService')), ($container->privates['App\\Validation\\AccessTokenValidator'] ?? $container->load('getAccessTokenValidatorService')));
    }
}
