<?php

namespace ContainerL9jLZrI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAssignScopeControllerActionService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\Gatekeeper\Scope\AssignScopeControllerAction' shared autowired service.
     *
     * @return \App\Controller\Gatekeeper\Scope\AssignScopeControllerAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/Gatekeeper/Scope/AssignScopeControllerAction.php';

        return $container->services['App\\Controller\\Gatekeeper\\Scope\\AssignScopeControllerAction'] = new \App\Controller\Gatekeeper\Scope\AssignScopeControllerAction();
    }
}
