<?php

namespace Container26vmqVw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlogDataPersisterService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\DataPersister\BlogDataPersister' shared autowired service.
     *
     * @return \App\DataPersister\BlogDataPersister
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/DataPersister/BlogDataPersister.php';

        return $container->privates['App\\DataPersister\\BlogDataPersister'] = new \App\DataPersister\BlogDataPersister(($container->privates['App\\DataPersister\\BlogDataPersister.inner'] ?? $container->load('getBlogDataPersister_InnerService')), ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));
    }
}
