<?php

namespace ContainerAaMMYnb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInitiateVerificationRequestValidatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.cTIhc.n.App\Validation\VerificationRequest\InitiateVerificationRequestValidator' shared service.
     *
     * @return \App\Validation\VerificationRequest\InitiateVerificationRequestValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.cTIhc.n": it references class "App\\Validation\\VerificationRequest\\InitiateVerificationRequestValidator" but no such service exists.');
    }
}
