<?php

namespace ContainerAaMMYnb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVerificationRequestImageLinkListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Listener\VerificationRequestImageLinkListener' shared autowired service.
     *
     * @return \App\Listener\VerificationRequestImageLinkListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Listener/VerificationRequestImageLinkListener.php';

        return $container->privates['App\\Listener\\VerificationRequestImageLinkListener'] = new \App\Listener\VerificationRequestImageLinkListener(($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
    }
}
