<?php

namespace ContainerEDaqtxz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator___A1PhService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator...a1_ph' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator...a1_ph'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AppClientController::new' => ['privates', '.service_locator._nRHRBM', 'get_ServiceLocator_NRHRBMService', true],
            'App\\Controller\\AuthorizationController::authRequest' => ['privates', '.service_locator.mwoT7nm', 'get_ServiceLocator_MwoT7nmService', true],
            'App\\Controller\\AuthorizationController::token' => ['privates', '.service_locator.e4ih1jg', 'get_ServiceLocator_E4ih1jgService', true],
            'App\\Controller\\AuthorizationController::tokenUser' => ['privates', '.service_locator.WrHDVk7', 'get_ServiceLocator_WrHDVk7Service', true],
            'App\\Controller\\AuthorizationController::verify' => ['privates', '.service_locator.SCdc4f4', 'get_ServiceLocator_SCdc4f4Service', true],
            'App\\Controller\\Gatekeeper\\Microservices\\AddScopeControllerAction::__invoke' => ['privates', '.service_locator.ysaaqti', 'get_ServiceLocator_YsaaqtiService', true],
            'App\\Controller\\Gatekeeper\\Microservices\\RegisterMicroserviceAction::__invoke' => ['privates', '.service_locator.c5iIMJ9', 'get_ServiceLocator_C5iIMJ9Service', true],
            'App\\Controller\\Gatekeeper\\Registration\\RegisterMSOwnerControllerAction::__invoke' => ['privates', '.service_locator.H4mPNd4', 'get_ServiceLocator_H4mPNd4Service', true],
            'App\\Controller\\Gatekeeper\\Registration\\VerifyAccountControllerAction::__invoke' => ['privates', '.service_locator.7yf5duC', 'get_ServiceLocator_7yf5duCService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\AppClientController:new' => ['privates', '.service_locator._nRHRBM', 'get_ServiceLocator_NRHRBMService', true],
            'App\\Controller\\AuthorizationController:authRequest' => ['privates', '.service_locator.mwoT7nm', 'get_ServiceLocator_MwoT7nmService', true],
            'App\\Controller\\AuthorizationController:token' => ['privates', '.service_locator.e4ih1jg', 'get_ServiceLocator_E4ih1jgService', true],
            'App\\Controller\\AuthorizationController:tokenUser' => ['privates', '.service_locator.WrHDVk7', 'get_ServiceLocator_WrHDVk7Service', true],
            'App\\Controller\\AuthorizationController:verify' => ['privates', '.service_locator.SCdc4f4', 'get_ServiceLocator_SCdc4f4Service', true],
            'App\\Controller\\Gatekeeper\\Microservices\\AddScopeControllerAction:__invoke' => ['privates', '.service_locator.ysaaqti', 'get_ServiceLocator_YsaaqtiService', true],
            'App\\Controller\\Gatekeeper\\Microservices\\AddScopeControllerAction' => ['privates', '.service_locator.ysaaqti', 'get_ServiceLocator_YsaaqtiService', true],
            'App\\Controller\\Gatekeeper\\Microservices\\RegisterMicroserviceAction:__invoke' => ['privates', '.service_locator.c5iIMJ9', 'get_ServiceLocator_C5iIMJ9Service', true],
            'App\\Controller\\Gatekeeper\\Microservices\\RegisterMicroserviceAction' => ['privates', '.service_locator.c5iIMJ9', 'get_ServiceLocator_C5iIMJ9Service', true],
            'App\\Controller\\Gatekeeper\\Registration\\RegisterMSOwnerControllerAction:__invoke' => ['privates', '.service_locator.H4mPNd4', 'get_ServiceLocator_H4mPNd4Service', true],
            'App\\Controller\\Gatekeeper\\Registration\\RegisterMSOwnerControllerAction' => ['privates', '.service_locator.H4mPNd4', 'get_ServiceLocator_H4mPNd4Service', true],
            'App\\Controller\\Gatekeeper\\Registration\\VerifyAccountControllerAction:__invoke' => ['privates', '.service_locator.7yf5duC', 'get_ServiceLocator_7yf5duCService', true],
            'App\\Controller\\Gatekeeper\\Registration\\VerifyAccountControllerAction' => ['privates', '.service_locator.7yf5duC', 'get_ServiceLocator_7yf5duCService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\AppClientController::new' => '?',
            'App\\Controller\\AuthorizationController::authRequest' => '?',
            'App\\Controller\\AuthorizationController::token' => '?',
            'App\\Controller\\AuthorizationController::tokenUser' => '?',
            'App\\Controller\\AuthorizationController::verify' => '?',
            'App\\Controller\\Gatekeeper\\Microservices\\AddScopeControllerAction::__invoke' => '?',
            'App\\Controller\\Gatekeeper\\Microservices\\RegisterMicroserviceAction::__invoke' => '?',
            'App\\Controller\\Gatekeeper\\Registration\\RegisterMSOwnerControllerAction::__invoke' => '?',
            'App\\Controller\\Gatekeeper\\Registration\\VerifyAccountControllerAction::__invoke' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AppClientController:new' => '?',
            'App\\Controller\\AuthorizationController:authRequest' => '?',
            'App\\Controller\\AuthorizationController:token' => '?',
            'App\\Controller\\AuthorizationController:tokenUser' => '?',
            'App\\Controller\\AuthorizationController:verify' => '?',
            'App\\Controller\\Gatekeeper\\Microservices\\AddScopeControllerAction:__invoke' => '?',
            'App\\Controller\\Gatekeeper\\Microservices\\AddScopeControllerAction' => '?',
            'App\\Controller\\Gatekeeper\\Microservices\\RegisterMicroserviceAction:__invoke' => '?',
            'App\\Controller\\Gatekeeper\\Microservices\\RegisterMicroserviceAction' => '?',
            'App\\Controller\\Gatekeeper\\Registration\\RegisterMSOwnerControllerAction:__invoke' => '?',
            'App\\Controller\\Gatekeeper\\Registration\\RegisterMSOwnerControllerAction' => '?',
            'App\\Controller\\Gatekeeper\\Registration\\VerifyAccountControllerAction:__invoke' => '?',
            'App\\Controller\\Gatekeeper\\Registration\\VerifyAccountControllerAction' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
