<?php

namespace ContainerEDaqtxz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_JGcLiRsService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored.jGcLiRs' shared service.
     *
     * @return \App\Controller\AppClientRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\AuthorizationController::authRequest()": the $appClientRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\AppClientRepository". Did you forget to add a use statement?');
    }
}
