<?php

namespace ContainerEDaqtxz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MwoT7nmService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.mwoT7nm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mwoT7nm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'appClientRepository' => ['privates', '.errored.jGcLiRs', NULL, 'Cannot determine controller argument for "App\\Controller\\AuthorizationController::authRequest()": the $appClientRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\AppClientRepository". Did you forget to add a use statement?'],
            'authRequestValidator' => ['privates', 'App\\Validation\\AuthRequestValidator', NULL, 'Cannot autowire service "App\\Validation\\AuthRequestValidator": argument "$appClientRepository" of method "__construct()" has type "App\\Validation\\AppClientRepository" but this class was not found.'],
            'encoder' => ['services', 'lexik_jwt_authentication.encoder', 'getLexikJwtAuthentication_EncoderService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'logger' => ['privates', 'monolog.logger', 'getMonolog_LoggerService', false],
        ], [
            'appClientRepository' => '?',
            'authRequestValidator' => 'App\\Validation\\AuthRequestValidator',
            'encoder' => '?',
            'entityManager' => '?',
            'logger' => '?',
        ]);
    }
}
