<?php

namespace ContainerEDaqtxz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthRequestValidatorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Validation\AuthRequestValidator' shared autowired service.
     *
     * @return \App\Validation\AuthRequestValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service "App\\Validation\\AuthRequestValidator": argument "$appClientRepository" of method "__construct()" has type "App\\Validation\\AppClientRepository" but this class was not found.');
    }
}
