<?php

namespace ContainerEDaqtxz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClientGeneratorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\ClientGenerator' shared autowired service.
     *
     * @return \App\Service\ClientGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/ClientGenerator.php';

        return $container->privates['App\\Service\\ClientGenerator'] = new \App\Service\ClientGenerator();
    }
}
