<?php

namespace ContainerEDaqtxz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMicroserviceRegistrationValidatorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Validation\MicroserviceRegistrationValidator' shared autowired service.
     *
     * @return \App\Validation\MicroserviceRegistrationValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Validation/MicroserviceRegistrationValidator.php';

        return $container->privates['App\\Validation\\MicroserviceRegistrationValidator'] = new \App\Validation\MicroserviceRegistrationValidator(($container->services['validator'] ?? $container->getValidatorService()), ($container->privates['App\\Repository\\MicroserviceRepository'] ?? $container->load('getMicroserviceRepositoryService')));
    }
}
