<?php

namespace ContainerEDaqtxz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMicroserviceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.c5iIMJ9.App\Entity\Microservice' shared service.
     *
     * @return \App\Entity\Microservice
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.c5iIMJ9": it references class "App\\Entity\\Microservice" but no such service exists.');
    }
}
