<?php

namespace ContainerEDaqtxz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScopeBodyValidatorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Validation\ScopeBodyValidator' shared autowired service.
     *
     * @return \App\Validation\ScopeBodyValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Validation/ScopeBodyValidator.php';

        return $container->privates['App\\Validation\\ScopeBodyValidator'] = new \App\Validation\ScopeBodyValidator();
    }
}
