<?php

namespace ContainerEDaqtxz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVerifyAccountControllerActionService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\Gatekeeper\Registration\VerifyAccountControllerAction' shared autowired service.
     *
     * @return \App\Controller\Gatekeeper\Registration\VerifyAccountControllerAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/Gatekeeper/Registration/VerifyAccountControllerAction.php';

        return $container->services['App\\Controller\\Gatekeeper\\Registration\\VerifyAccountControllerAction'] = new \App\Controller\Gatekeeper\Registration\VerifyAccountControllerAction();
    }
}
