<?php

namespace ContainerCkZhE8x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CTcxC7_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cTcxC7.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cTcxC7.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'data' => ['privates', 'App\\Model\\Scope', 'getScopeService', true],
            'microserviceScopeRepository' => ['privates', 'App\\Repository\\MicroserviceScopeRepository', 'getMicroserviceScopeRepositoryService', true],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'data' => 'App\\Model\\Scope',
            'microserviceScopeRepository' => 'App\\Repository\\MicroserviceScopeRepository',
            'security' => '?',
        ]);
    }
}
