<?php

namespace ContainerCkZhE8x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I0zWq0VService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.i0zWq0V' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.i0zWq0V'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'authorizationCodeValidator' => ['privates', 'App\\Validation\\AuthorizationCodeValidator', 'getAuthorizationCodeValidatorService', true],
            'encoder' => ['services', 'lexik_jwt_authentication.encoder', 'getLexikJwtAuthentication_EncoderService', true],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
            'urlGenerator' => ['privates', 'api_platform.router', 'getApiPlatform_RouterService', false],
        ], [
            'authorizationCodeValidator' => 'App\\Validation\\AuthorizationCodeValidator',
            'encoder' => '?',
            'security' => '?',
            'urlGenerator' => '?',
        ]);
    }
}
