<?php

namespace ContainerCkZhE8x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CeTPPeMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ceTPPeM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ceTPPeM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'appClient' => ['privates', '.errored..service_locator.ceTPPeM.App\\Entity\\Microservice', NULL, 'Cannot autowire service ".service_locator.ceTPPeM": it references class "App\\Entity\\Microservice" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'appClient' => 'App\\Entity\\Microservice',
            'entityManager' => '?',
        ]);
    }
}
