<?php

namespace ContainerCkZhE8x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NasEdVpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nasEdVp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nasEdVp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'appClientRepository' => ['privates', 'App\\Repository\\MicroserviceRepository', 'getMicroserviceRepositoryService', true],
        ], [
            'appClientRepository' => 'App\\Repository\\MicroserviceRepository',
        ]);
    }
}
