<?php

namespace ContainerCkZhE8x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JjEb6q_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JjEb6q.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JjEb6q.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'microserviceScopeRepository' => ['privates', 'App\\Repository\\MicroserviceScopeRepository', 'getMicroserviceScopeRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'microserviceScopeRepository' => 'App\\Repository\\MicroserviceScopeRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
