<?php

namespace ContainerCkZhE8x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WfcS1NVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wfcS1NV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wfcS1NV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'microserviceRepository' => ['privates', 'App\\Repository\\MicroserviceRepository', 'getMicroserviceRepositoryService', true],
            'microserviceScopeRepository' => ['privates', 'App\\Repository\\MicroserviceScopeRepository', 'getMicroserviceScopeRepositoryService', true],
        ], [
            'entityManager' => '?',
            'microserviceRepository' => 'App\\Repository\\MicroserviceRepository',
            'microserviceScopeRepository' => 'App\\Repository\\MicroserviceScopeRepository',
        ]);
    }
}
