<?php

namespace ContainerCkZhE8x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AgZ0e_FService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.agZ0e.f' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.agZ0e.f'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'authRequestValidator' => ['privates', 'App\\Validation\\AuthRequestValidator', 'getAuthRequestValidatorService', true],
            'encoder' => ['services', 'lexik_jwt_authentication.encoder', 'getLexikJwtAuthentication_EncoderService', true],
        ], [
            'authRequestValidator' => 'App\\Validation\\AuthRequestValidator',
            'encoder' => '?',
        ]);
    }
}
