<?php

namespace ContainerCkZhE8x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7vAz8OQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7vAz8OQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7vAz8OQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'microserviceRepository' => ['privates', 'App\\Repository\\MicroserviceRepository', 'getMicroserviceRepositoryService', true],
            'microserviceScopeRepository' => ['privates', 'App\\Repository\\MicroserviceScopeRepository', 'getMicroserviceScopeRepositoryService', true],
        ], [
            'microserviceRepository' => 'App\\Repository\\MicroserviceRepository',
            'microserviceScopeRepository' => 'App\\Repository\\MicroserviceScopeRepository',
        ]);
    }
}
