<?php

namespace ContainerCkZhE8x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UScHSuLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UScHSuL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UScHSuL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'microserviceRepository' => ['privates', 'App\\Repository\\MicroserviceRepository', 'getMicroserviceRepositoryService', true],
            'microserviceScopeFactory' => ['privates', 'App\\Factory\\MicroserviceScopeFactory', 'getMicroserviceScopeFactoryService', true],
            'microserviceScopeRepository' => ['privates', 'App\\Repository\\MicroserviceScopeRepository', 'getMicroserviceScopeRepositoryService', true],
            'scopeBodyValidator' => ['privates', 'App\\Validation\\ScopeBodyValidator', 'getScopeBodyValidatorService', true],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'entityManager' => '?',
            'microserviceRepository' => 'App\\Repository\\MicroserviceRepository',
            'microserviceScopeFactory' => 'App\\Factory\\MicroserviceScopeFactory',
            'microserviceScopeRepository' => 'App\\Repository\\MicroserviceScopeRepository',
            'scopeBodyValidator' => 'App\\Validation\\ScopeBodyValidator',
            'security' => '?',
        ]);
    }
}
