<?php

namespace ContainerCkZhE8x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthorizationControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Gatekeeper\Auth\AuthorizationController' shared autowired service.
     *
     * @return \App\Controller\Gatekeeper\Auth\AuthorizationController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Gatekeeper/Auth/AuthorizationController.php';

        $container->services['App\\Controller\\Gatekeeper\\Auth\\AuthorizationController'] = $instance = new \App\Controller\Gatekeeper\Auth\AuthorizationController();

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\Gatekeeper\\Auth\\AuthorizationController', $container));

        return $instance;
    }
}
