<?php

namespace ContainerCkZhE8x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClientGuardAuthenticatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Security\ClientGuardAuthenticator' shared autowired service.
     *
     * @return \App\Security\ClientGuardAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/EntryPoint/AuthenticationEntryPointInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-guard/AuthenticatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-guard/AbstractGuardAuthenticator.php';
        include_once \dirname(__DIR__, 4).'/src/Security/ClientGuardAuthenticator.php';

        return $container->privates['App\\Security\\ClientGuardAuthenticator'] = new \App\Security\ClientGuardAuthenticator(($container->privates['App\\Repository\\MicroserviceRepository'] ?? $container->load('getMicroserviceRepositoryService')));
    }
}
