<?php

namespace ContainerCkZhE8x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClaimFormTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\ClaimFormType' shared autowired service.
     *
     * @return \App\Form\ClaimFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/ClaimFormType.php';

        return $container->privates['App\\Form\\ClaimFormType'] = new \App\Form\ClaimFormType();
    }
}
