<?php

namespace ContainerCkZhE8x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetUserInfoControllerActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Gatekeeper\Auth\GetUserInfoControllerAction' shared autowired service.
     *
     * @return \App\Controller\Gatekeeper\Auth\GetUserInfoControllerAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/Gatekeeper/Auth/GetUserInfoControllerAction.php';

        return $container->services['App\\Controller\\Gatekeeper\\Auth\\GetUserInfoControllerAction'] = new \App\Controller\Gatekeeper\Auth\GetUserInfoControllerAction();
    }
}
