<?php

namespace ContainerCkZhE8x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getListScopeControllerActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Gatekeeper\Scope\ListScopeControllerAction' shared autowired service.
     *
     * @return \App\Controller\Gatekeeper\Scope\ListScopeControllerAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/Gatekeeper/Scope/ListScopeControllerAction.php';

        return $container->services['App\\Controller\\Gatekeeper\\Scope\\ListScopeControllerAction'] = new \App\Controller\Gatekeeper\Scope\ListScopeControllerAction();
    }
}
