<?php

namespace ContainerCkZhE8x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMicroservice2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ceTPPeM.App\Entity\Microservice' shared service.
     *
     * @return \App\Entity\Microservice
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.ceTPPeM": it references class "App\\Entity\\Microservice" but no such service exists.');
    }
}
