<?php

namespace ContainerCkZhE8x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMicroserviceSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventSubscriber\MicroserviceSubscriber' shared autowired service.
     *
     * @return \App\EventSubscriber\MicroserviceSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventSubscriber/MicroserviceSubscriber.php';
        include_once \dirname(__DIR__, 4).'/src/Service/ClientGenerator.php';
        include_once \dirname(__DIR__, 4).'/src/Validation/MicroserviceRegistrationValidator.php';

        return $container->privates['App\\EventSubscriber\\MicroserviceSubscriber'] = new \App\EventSubscriber\MicroserviceSubscriber(($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')), new \App\Service\ClientGenerator(), new \App\Validation\MicroserviceRegistrationValidator(($container->services['validator'] ?? $container->getValidatorService()), ($container->privates['App\\Repository\\MicroserviceRepository'] ?? $container->load('getMicroserviceRepositoryService'))), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
