<?php

namespace ContainerCkZhE8x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegisterClientAdminControllerActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Gatekeeper\Registration\RegisterClientAdminControllerAction' shared autowired service.
     *
     * @return \App\Controller\Gatekeeper\Registration\RegisterClientAdminControllerAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/Gatekeeper/Registration/RegisterClientAdminControllerAction.php';

        return $container->services['App\\Controller\\Gatekeeper\\Registration\\RegisterClientAdminControllerAction'] = new \App\Controller\Gatekeeper\Registration\RegisterClientAdminControllerAction();
    }
}
