<?php

namespace ContainerCkZhE8x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScopeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Model\Scope' shared autowired service.
     *
     * @return \App\Model\Scope
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Model/Scope.php';

        return $container->privates['App\\Model\\Scope'] = new \App\Model\Scope();
    }
}
