<?php

namespace ContainerCkZhE8x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTokenControllerActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Gatekeeper\Auth\TokenControllerAction' shared autowired service.
     *
     * @return \App\Controller\Gatekeeper\Auth\TokenControllerAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/Gatekeeper/Auth/TokenControllerAction.php';

        return $container->services['App\\Controller\\Gatekeeper\\Auth\\TokenControllerAction'] = new \App\Controller\Gatekeeper\Auth\TokenControllerAction();
    }
}
