<?php

namespace ContainerK3sHzsJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UTpHpL_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UTpHpL.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UTpHpL.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'data' => ['privates', '.errored..service_locator.UTpHpL..App\\Entity\\Blog', NULL, 'Cannot autowire service ".service_locator.UTpHpL.": it references class "App\\Entity\\Blog" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'data' => 'App\\Entity\\Blog',
            'entityManager' => '?',
        ]);
    }
}
