<?php

namespace ContainerK3sHzsJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUpdateVerificationRequestActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Locastic\VerificationRequest\UpdateVerificationRequestAction' shared autowired service.
     *
     * @return \App\Controller\Locastic\VerificationRequest\UpdateVerificationRequestAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/Locastic/VerificationRequest/UpdateVerificationRequestAction.php';

        return $container->services['App\\Controller\\Locastic\\VerificationRequest\\UpdateVerificationRequestAction'] = new \App\Controller\Locastic\VerificationRequest\UpdateVerificationRequestAction();
    }
}
