<?php

namespace ContainerQlbi1Di;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInitiateVerificationRequestSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventSubscriber\InitiateVerificationRequestSubscriber' shared autowired service.
     *
     * @return \App\EventSubscriber\InitiateVerificationRequestSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventSubscriber/InitiateVerificationRequestSubscriber.php';
        include_once \dirname(__DIR__, 4).'/src/Service/FileUploader.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/string/Slugger/SluggerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/string/Slugger/AsciiSlugger.php';

        return $container->privates['App\\EventSubscriber\\InitiateVerificationRequestSubscriber'] = new \App\EventSubscriber\InitiateVerificationRequestSubscriber(new \App\Service\FileUploader((\dirname(__DIR__, 4).'/public/upload/image'), ($container->privates['slugger'] ?? ($container->privates['slugger'] = new \Symfony\Component\String\Slugger\AsciiSlugger('en')))), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
