<?php

namespace ContainerVBkIzz8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_C4rouETService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.C4rouET' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.C4rouET'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AppClientController::new' => ['privates', '.service_locator._nRHRBM', 'get_ServiceLocator_NRHRBMService', true],
            'App\\Controller\\AuthorizationController::token' => ['privates', '.service_locator.cAxpBD.', 'get_ServiceLocator_CAxpBD_Service', true],
            'App\\Controller\\Gatekeeper\\Microservices\\AddScopeControllerAction::__invoke' => ['privates', '.service_locator.UScHSuL', 'get_ServiceLocator_UScHSuLService', true],
            'App\\Controller\\Gatekeeper\\Microservices\\RegisterMicroserviceAction::__invoke' => ['privates', '.service_locator.c5iIMJ9', 'get_ServiceLocator_C5iIMJ9Service', true],
            'App\\Controller\\Gatekeeper\\Registration\\RegisterAdminControllerAction::__invoke' => ['privates', '.service_locator.H4mPNd4', 'get_ServiceLocator_H4mPNd4Service', true],
            'App\\Controller\\Gatekeeper\\Registration\\RegisterClientAdminControllerAction::__invoke' => ['privates', '.service_locator.H4mPNd4', 'get_ServiceLocator_H4mPNd4Service', true],
            'App\\Controller\\Gatekeeper\\Registration\\RegisterMSOwnerControllerAction::__invoke' => ['privates', '.service_locator.H4mPNd4', 'get_ServiceLocator_H4mPNd4Service', true],
            'App\\Controller\\Gatekeeper\\Registration\\VerifyAccountControllerAction::verify' => ['privates', '.service_locator.7yf5duC', 'get_ServiceLocator_7yf5duCService', true],
            'App\\Controller\\Gatekeeper\\Scope\\AssignScopeControllerAction::__invoke' => ['privates', '.service_locator.5rLwUqy', 'get_ServiceLocator_5rLwUqyService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\AppClientController:new' => ['privates', '.service_locator._nRHRBM', 'get_ServiceLocator_NRHRBMService', true],
            'App\\Controller\\AuthorizationController:token' => ['privates', '.service_locator.cAxpBD.', 'get_ServiceLocator_CAxpBD_Service', true],
            'App\\Controller\\Gatekeeper\\Microservices\\AddScopeControllerAction:__invoke' => ['privates', '.service_locator.UScHSuL', 'get_ServiceLocator_UScHSuLService', true],
            'App\\Controller\\Gatekeeper\\Microservices\\AddScopeControllerAction' => ['privates', '.service_locator.UScHSuL', 'get_ServiceLocator_UScHSuLService', true],
            'App\\Controller\\Gatekeeper\\Microservices\\RegisterMicroserviceAction:__invoke' => ['privates', '.service_locator.c5iIMJ9', 'get_ServiceLocator_C5iIMJ9Service', true],
            'App\\Controller\\Gatekeeper\\Microservices\\RegisterMicroserviceAction' => ['privates', '.service_locator.c5iIMJ9', 'get_ServiceLocator_C5iIMJ9Service', true],
            'App\\Controller\\Gatekeeper\\Registration\\RegisterAdminControllerAction:__invoke' => ['privates', '.service_locator.H4mPNd4', 'get_ServiceLocator_H4mPNd4Service', true],
            'App\\Controller\\Gatekeeper\\Registration\\RegisterUserControllerAction' => ['privates', '.service_locator.H4mPNd4', 'get_ServiceLocator_H4mPNd4Service', true],
            'App\\Controller\\Gatekeeper\\Registration\\RegisterClientAdminControllerAction:__invoke' => ['privates', '.service_locator.H4mPNd4', 'get_ServiceLocator_H4mPNd4Service', true],
            'App\\Controller\\Gatekeeper\\Registration\\RegisterClientAdminControllerAction' => ['privates', '.service_locator.H4mPNd4', 'get_ServiceLocator_H4mPNd4Service', true],
            'App\\Controller\\Gatekeeper\\Registration\\RegisterMSOwnerControllerAction:__invoke' => ['privates', '.service_locator.H4mPNd4', 'get_ServiceLocator_H4mPNd4Service', true],
            'App\\Controller\\Gatekeeper\\Registration\\RegisterMSOwnerControllerAction' => ['privates', '.service_locator.H4mPNd4', 'get_ServiceLocator_H4mPNd4Service', true],
            'App\\Controller\\Gatekeeper\\Registration\\VerifyAccountControllerAction:verify' => ['privates', '.service_locator.7yf5duC', 'get_ServiceLocator_7yf5duCService', true],
            'App\\Controller\\Gatekeeper\\Scope\\AssignScopeControllerAction:__invoke' => ['privates', '.service_locator.5rLwUqy', 'get_ServiceLocator_5rLwUqyService', true],
            'App\\Controller\\Gatekeeper\\Scope\\AssignScopeControllerAction' => ['privates', '.service_locator.5rLwUqy', 'get_ServiceLocator_5rLwUqyService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\AppClientController::new' => '?',
            'App\\Controller\\AuthorizationController::token' => '?',
            'App\\Controller\\Gatekeeper\\Microservices\\AddScopeControllerAction::__invoke' => '?',
            'App\\Controller\\Gatekeeper\\Microservices\\RegisterMicroserviceAction::__invoke' => '?',
            'App\\Controller\\Gatekeeper\\Registration\\RegisterAdminControllerAction::__invoke' => '?',
            'App\\Controller\\Gatekeeper\\Registration\\RegisterClientAdminControllerAction::__invoke' => '?',
            'App\\Controller\\Gatekeeper\\Registration\\RegisterMSOwnerControllerAction::__invoke' => '?',
            'App\\Controller\\Gatekeeper\\Registration\\VerifyAccountControllerAction::verify' => '?',
            'App\\Controller\\Gatekeeper\\Scope\\AssignScopeControllerAction::__invoke' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AppClientController:new' => '?',
            'App\\Controller\\AuthorizationController:token' => '?',
            'App\\Controller\\Gatekeeper\\Microservices\\AddScopeControllerAction:__invoke' => '?',
            'App\\Controller\\Gatekeeper\\Microservices\\AddScopeControllerAction' => '?',
            'App\\Controller\\Gatekeeper\\Microservices\\RegisterMicroserviceAction:__invoke' => '?',
            'App\\Controller\\Gatekeeper\\Microservices\\RegisterMicroserviceAction' => '?',
            'App\\Controller\\Gatekeeper\\Registration\\RegisterAdminControllerAction:__invoke' => '?',
            'App\\Controller\\Gatekeeper\\Registration\\RegisterUserControllerAction' => '?',
            'App\\Controller\\Gatekeeper\\Registration\\RegisterClientAdminControllerAction:__invoke' => '?',
            'App\\Controller\\Gatekeeper\\Registration\\RegisterClientAdminControllerAction' => '?',
            'App\\Controller\\Gatekeeper\\Registration\\RegisterMSOwnerControllerAction:__invoke' => '?',
            'App\\Controller\\Gatekeeper\\Registration\\RegisterMSOwnerControllerAction' => '?',
            'App\\Controller\\Gatekeeper\\Registration\\VerifyAccountControllerAction:verify' => '?',
            'App\\Controller\\Gatekeeper\\Scope\\AssignScopeControllerAction:__invoke' => '?',
            'App\\Controller\\Gatekeeper\\Scope\\AssignScopeControllerAction' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
