<?php

namespace ContainerVBkIzz8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5rLwUqyService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.5rLwUqy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5rLwUqy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'assignedScopeValidator' => ['privates', 'App\\Validation\\AssignedScopeValidator', 'getAssignedScopeValidatorService', true],
            'data' => ['privates', 'App\\Model\\Scope', 'getScopeService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'assignedScopeValidator' => 'App\\Validation\\AssignedScopeValidator',
            'data' => 'App\\Model\\Scope',
            'entityManager' => '?',
            'security' => '?',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
