<?php

namespace ContainerVBkIzz8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAssignedScopeValidatorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Validation\AssignedScopeValidator' shared autowired service.
     *
     * @return \App\Validation\AssignedScopeValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Validation/AssignedScopeValidator.php';

        return $container->privates['App\\Validation\\AssignedScopeValidator'] = new \App\Validation\AssignedScopeValidator();
    }
}
