<?php

namespace ContainerVBkIzz8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAppClientTypeService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Form\AppClientType' shared autowired service.
     *
     * @return \App\Form\AppClientType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/AppClientType.php';

        return $container->privates['App\\Form\\AppClientType'] = new \App\Form\AppClientType();
    }
}
