<?php

namespace ContainerVBkIzz8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGatekeeperMailerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\GatekeeperMailer' shared autowired service.
     *
     * @return \App\Service\GatekeeperMailer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/GatekeeperMailer.php';

        return $container->privates['App\\Service\\GatekeeperMailer'] = new \App\Service\GatekeeperMailer(($container->privates['parameter_bag'] ?? ($container->privates['parameter_bag'] = new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container))), ($container->services['lexik_jwt_authentication.encoder'] ?? $container->load('getLexikJwtAuthentication_EncoderService')), ($container->services['router'] ?? $container->getRouterService()), ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService')));
    }
}
