<?php

namespace ContainerVBkIzz8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMicroserviceSubscriberService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\EventSubscriber\MicroserviceSubscriber' shared autowired service.
     *
     * @return \App\EventSubscriber\MicroserviceSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventSubscriber/MicroserviceSubscriber.php';
        include_once \dirname(__DIR__, 4).'/src/Service/ClientGenerator.php';

        return $container->privates['App\\EventSubscriber\\MicroserviceSubscriber'] = new \App\EventSubscriber\MicroserviceSubscriber(($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')), ($container->privates['App\\Service\\ClientGenerator'] ?? ($container->privates['App\\Service\\ClientGenerator'] = new \App\Service\ClientGenerator())), ($container->privates['App\\Validation\\MicroserviceRegistrationValidator'] ?? $container->load('getMicroserviceRegistrationValidatorService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
