<?php

namespace ContainerVBkIzz8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegisterMSOwnerControllerActionService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\Gatekeeper\Registration\RegisterMSOwnerControllerAction' shared autowired service.
     *
     * @return \App\Controller\Gatekeeper\Registration\RegisterMSOwnerControllerAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/Gatekeeper/Registration/RegisterMSOwnerControllerAction.php';

        return $container->services['App\\Controller\\Gatekeeper\\Registration\\RegisterMSOwnerControllerAction'] = new \App\Controller\Gatekeeper\Registration\RegisterMSOwnerControllerAction();
    }
}
