<?php

namespace ContainerH1xGrJg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IgGC8lqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.igGC8lq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.igGC8lq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'data' => ['privates', '.errored..service_locator.igGC8lq.App\\Entity\\VerificationRequest', NULL, 'Cannot autowire service ".service_locator.igGC8lq": it references class "App\\Entity\\VerificationRequest" but no such service exists.'],
            'verificationRequestResponseBuilder' => ['privates', 'App\\Utility\\VerificationRequestResponseBuilder', 'getVerificationRequestResponseBuilderService', true],
        ], [
            'data' => 'App\\Entity\\VerificationRequest',
            'verificationRequestResponseBuilder' => 'App\\Utility\\VerificationRequestResponseBuilder',
        ]);
    }
}
