<?php

namespace ContainerH1xGrJg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_V4VA91oService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.v4VA91o' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.v4VA91o'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'eventDispatcher' => ['services', 'event_dispatcher', 'getEventDispatcherService', false],
            'logger' => ['privates', 'monolog.logger', 'getMonolog_LoggerService', false],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
            'verificationRequestResponseBuilder' => ['privates', 'App\\Utility\\VerificationRequestResponseBuilder', 'getVerificationRequestResponseBuilderService', true],
        ], [
            'eventDispatcher' => '?',
            'logger' => '?',
            'security' => '?',
            'verificationRequestResponseBuilder' => 'App\\Utility\\VerificationRequestResponseBuilder',
        ]);
    }
}
