<?php

namespace ContainerH1xGrJg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVerificationRequestResponseBuilderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Utility\VerificationRequestResponseBuilder' shared autowired service.
     *
     * @return \App\Utility\VerificationRequestResponseBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Utility/VerificationRequestResponseBuilder.php';

        return $container->privates['App\\Utility\\VerificationRequestResponseBuilder'] = new \App\Utility\VerificationRequestResponseBuilder(($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
    }
}
