<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA7aGiMe\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA7aGiMe/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerA7aGiMe.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerA7aGiMe\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerA7aGiMe\App_KernelTestDebugContainer([
    'container.build_hash' => 'A7aGiMe',
    'container.build_id' => '6d5229e9',
    'container.build_time' => 1608124122,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA7aGiMe');
