<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container26vmqVw\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container26vmqVw/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/Container26vmqVw.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\Container26vmqVw\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \Container26vmqVw\App_KernelTestDebugContainer([
    'container.build_hash' => '26vmqVw',
    'container.build_id' => '81690287',
    'container.build_time' => 1607997336,
], __DIR__.\DIRECTORY_SEPARATOR.'Container26vmqVw');
