<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL9jLZrI\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL9jLZrI/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerL9jLZrI.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerL9jLZrI\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerL9jLZrI\App_KernelTestDebugContainer([
    'container.build_hash' => 'L9jLZrI',
    'container.build_id' => 'b87ba4a0',
    'container.build_time' => 1604326479,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL9jLZrI');
