<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_client_new' => [[], ['_controller' => 'App\\Controller\\AppClientController::new'], [], [['text', '/app-client/new']], [], []],
    'app_token' => [[], ['_controller' => 'App\\Controller\\AuthorizationController::token'], [], [['text', '/api/auth']], [], []],
    'app_dashboard' => [[], ['_controller' => 'App\\Controller\\DashboardController::dashboard'], [], [['text', '/dashboard']], [], []],
    'account_verify' => [[], ['_controller' => 'App\\Controller\\Gatekeeper\\Registration\\VerifyAccountControllerAction::verify'], [], [['text', '/account/verify']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
    'api_entrypoint' => [['index', '_format'], ['_controller' => 'api_platform.action.entrypoint', '_format' => '', '_api_respond' => 'true', 'index' => 'index'], ['index' => 'index'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', 'index', 'index', true], ['text', '/api']], [], []],
    'api_doc' => [['_format'], ['_controller' => 'api_platform.action.documentation', '_format' => '', '_api_respond' => 'true'], [], [['variable', '.', '[^/]++', '_format', true], ['text', '/api/docs']], [], []],
    'api_jsonld_context' => [['shortName', '_format'], ['_controller' => 'api_platform.jsonld.action.context', '_format' => 'jsonld', '_api_respond' => 'true'], ['shortName' => '.+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '.+', 'shortName', true], ['text', '/api/contexts']], [], []],
    'api_registrations_register_msowner_collection' => [[], ['_controller' => 'App\\Controller\\Gatekeeper\\Registration\\RegisterMSOwnerControllerAction', '_format' => null, '_api_resource_class' => 'App\\Model\\Registration\\Registration', '_api_collection_operation_name' => 'register_msowner'], [], [['text', '/api/register_ms_owner']], [], []],
    'api_registrations_register_admin_collection' => [[], ['_controller' => 'App\\Controller\\Gatekeeper\\Registration\\RegisterUserControllerAction', '_format' => null, '_api_resource_class' => 'App\\Model\\Registration\\Registration', '_api_collection_operation_name' => 'register_admin'], [], [['text', '/api/register_admin']], [], []],
    'api_registrations_register_client_admin_collection' => [[], ['_controller' => 'App\\Controller\\Gatekeeper\\Registration\\RegisterClientAdminControllerAction', '_format' => null, '_api_resource_class' => 'App\\Model\\Registration\\Registration', '_api_collection_operation_name' => 'register_client_admin'], [], [['text', '/api/register_client_admin']], [], []],
    'api_account_verifications_gk_verify_account_item' => [[], ['_controller' => 'App\\Controller\\Gatekeeper\\Registration\\VerifyAccountControllerAction', '_format' => null, '_api_resource_class' => 'App\\Model\\Registration\\AccountVerification', '_api_item_operation_name' => 'gk_verify_account', '_api_receive' => false], [], [['text', '/api/gk_verify_account']], [], []],
    'api_scopes_assign_scope_collection' => [['id'], ['_controller' => 'App\\Controller\\Gatekeeper\\Scope\\AssignScopeControllerAction', '_format' => null, '_api_resource_class' => 'App\\Model\\Scope', '_api_collection_operation_name' => 'assign_scope'], [], [['text', '/assign_scope'], ['variable', '/', '[^/]++', 'id', true], ['text', '/api/users']], [], []],
    'api_microservices_register_microservice_collection' => [[], ['_controller' => 'App\\Controller\\Gatekeeper\\Microservices\\RegisterMicroserviceAction', '_format' => null, '_api_resource_class' => 'App\\Entity\\Microservice', '_api_collection_operation_name' => 'register_microservice'], [], [['text', '/api/gk_register_microservice']], [], []],
    'api_microservice_scopes_add_scope_item' => [['microserviceId'], ['_controller' => 'App\\Controller\\Gatekeeper\\Microservices\\AddScopeControllerAction', '_format' => null, '_api_resource_class' => 'App\\Entity\\MicroserviceScope', '_api_item_operation_name' => 'add_scope', '_api_receive' => false], [], [['text', '/add_scope'], ['variable', '/', '[^/]++', 'microserviceId', true], ['text', '/api/microservices']], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\DashboardController::dashboard'], [], [['text', '/']], [], []],
    'authentication_token' => [[], [], [], [['text', '/gk_ms_owner/auth']], [], []],
];
