<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAeWjmhS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAeWjmhS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAeWjmhS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAeWjmhS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAeWjmhS\App_KernelDevDebugContainer([
    'container.build_hash' => 'AeWjmhS',
    'container.build_id' => 'dda89b7a',
    'container.build_time' => 1608123723,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAeWjmhS');
