<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBQIoBOv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBQIoBOv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBQIoBOv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBQIoBOv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBQIoBOv\App_KernelDevDebugContainer([
    'container.build_hash' => 'BQIoBOv',
    'container.build_id' => '4f940791',
    'container.build_time' => 1608143519,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBQIoBOv');
