<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXxHCdUP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXxHCdUP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXxHCdUP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXxHCdUP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXxHCdUP\App_KernelDevDebugContainer([
    'container.build_hash' => 'XxHCdUP',
    'container.build_id' => 'd0caf904',
    'container.build_time' => 1607921347,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXxHCdUP');
